### ISSUE TITLE
Correct invalid nesting anchor tags when listing transactions

### ISSUE THREAD

**Issue by ckniffen** [ripple/explorer#222]
The `AccountTransactionsTable`, `TokenTransactionsTable`, and `Ledger` components all use nested `<a>` tags.  This is invalid HTML and React will throw warnings.  Instead a technique needs to be used where an element is positioned absolute and all "nested" links sit on top of it.

The approach is detailed here. https://bdwm.be/html5-alternative-nested-anchor-tags/

Ex.

``` tsx
<li key={tx.hash}
  className={`transaction-li tx-type ${tx.type}`}
>
  <Link to={`/transactions/${tx.hash}`} className="transaction-whole" />
  <div className="upper">
      //...
  </div>
  <div className="details">
    <a href="whatever">Whatever</a>
    //...
  </div>
</li>
```

```scss
li.transaction-li {
  a {
    position: relative;
    z-index: 10;
  }

  a.transaction-whole {
    position: absolute;
    z-index: 5;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
  }
}
```
